--- 
config: 
  name: cjdname
foo: bar
fortune: 
  messages: 
    - "People are naturally attracted to you."
    - "You learn from your mistakes... You will learn a lot today."
hello: world

workshop: 
  contentURL: "https://workshop-content.cfapps.io"
  title: "Pivotal Cloud Foundry Workshop"
  date: "May 24, 2017"
  description: "This workshop will cover the ..."
  customerLogo: "https://www.cvshealth.com/sites/default/themes/cvs/img/logo-cvs-health-hd.png"
  instructors: 
    - 
      name: "Chris Decelles1"
      title: "Sr. Platform Architect"
      email: cdecelles@pivotal.io
      phone: "603.512.5616"
  resources:
    -
      title: "Pivotal Network"
      url: "https://network.pivotal.io/"
    -
      title: "Pivotal Documentation"
      url: "http://docs.pivotal.io/"
    -
      title: "cf CLI Documentation"
      url: "https://docs.pivotal.io/pivotalcf/cf-cli/getting-started.html"
    -
      title: "Manifest Documentation"
      url: "https://docs.pivotal.io/pivotalcf/devguide/deploy-apps/manifest.html"
    -
      title: "Spring Documentation"
      url: "https://spring.io/docs"
    -
      title: "Spring Initializr"
      url: "http://start.spring.io/"
    -
      title: "Pivotal Web Services"
      url: "https://run.pivotal.io/"
  requirements:
    -
      title: "Test"
      requirement:
        -
          content: "content 1 link"
        -
          content: "content 2 link"
    -
      title: "CLI"
      requirement:
      -
        content: "content 3 link"
      -
        content: "content 4 link"
  sessions:
    - 
      id: "day1"
      name: "Agenda"
      description: "Agenda Content"
      topics:
      -
        id: "springboot"
        title: "Spring Boot"
      -
        id: "80-cs-spring-boot-basics"
      -
        id: "82-cs-spring-boot-adv"
      -
        id: "actuator"
      -
        id: "spring-data-rest"
      -
        id: "scs"
        title: "Spring Cloud Services"
      -
        id: "config"
      -
        id: "service-discovery"
      -
        id: "circuit-breakers"
