--- 
config: 
  name: cjdname
workshop: 
  contentURL: "https://workshop-content.cfapps.io"
  title: "Pivotal Cloud Foundry Workshop"
  date: "March 14, 2017"
  description: "This workshop will cover the ..."
  customerLogo: "https://www.putnam.com/static/img/putnam-logo.svg"
  instructors: 
    - 
      name: "John Ferguson"
      title: "Sr. Mgr Platform Architecture"
      email: jferguson@pivotal.io
  resources:
    -
      title: "Pivotal Network"
      url: "https://network.pivotal.io/"
    -
      title: "Pivotal Documentation"
      url: "http://docs.pivotal.io/"
    -
      title: "cf CLI Documentation"
      url: "https://docs.pivotal.io/pivotalcf/cf-cli/getting-started.html"
    -
      title: "Manifest Documentation"
      url: "https://docs.pivotal.io/pivotalcf/devguide/deploy-apps/manifest.html"
    -
      title: "Spring Documentation"
      url: "https://spring.io/docs"
    -
      title: "Spring Initializr"
      url: "http://start.spring.io/"
    -
      title: "Pivotal Web Services"
      url: "https://run.pivotal.io/"
  requirements:
    -
      title: "Test"
      requirement:
        -
          content: "content 1 link"
        -
          content: "content 2 link"
    -
      title: "CLI"
      requirement:
      -
        content: "content 3 link"
      -
        content: "content 4 link"
  sessions:
    - 
      id: "day1"
      name: "Agenda"
      description: "Content for March 14, 2017"
      topics:
      -
        id: "session1"
        title: "9:15 - 10:00 - Pivotal Overview - Trends/Learnings"
      -
        id: "pcfd-intro"
      -
        id: "session2"
        title: "10:00 - 11:00 - Putnam to discuss current initiatives"
      -
        id: "session3"
        title: "11:00 - 11:30 - Pivotal Labs overview"
      -
        id: "session4"
        title: "11:30 - 12:15 - Pivotal Cloud Foundry Architecture"
      -
        id: "pcfd-arch"
      -
        id: "session5"
        title: "12:15 - 1:00 - Lunch"
      -
        id: "session6"
        title: "1:00 - 2:45 - Developer Agility"
      -
        id: "14-services"
      -
        id: "26-elastic-runtime"
      -
        id: "session7"
        title: "2:45 - 3:00 - Break"
      -
        id: "session8"
        title: "3:00 - 4:45 - Cloud Native Operations"
      -
        id: "20a-opsmgr-and-bosh-short"
      -
        id: "pcfa-bosh"
      -
        id: "pcfa-buildpack"
      -
        id: "session9"
        title: "4:45 - 5:00 - Next Steps"
